[package]
name = "safespace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.1.0", path = "../image" }
rand = "0.8.5"
once_cell = "1.16.0"

[workspace]
members = [
"bin",
]
